### ISSUE TITLE
Slow Performance / Lots of Lag When Typing a Response in Composer

### ISSUE THREAD

**Issue by xoniq** [nylas/N1#1069]
I experience a lot of slowdowns while typing a reply in a simple conversation. During typing is goes slower and slower. I don't see increased CPU or RAM usage. It's only the typing, if I select something using the keyboard it's just fine.

**Comment by bengotow** [comment]
Hi @crxdelsol — thanks for reporting this. To help us narrow this down, could you add:

- How long is your reply? Are we talking < 1000 characters or many more?
- Is performance better when typing new messages vs. replies to existing messages?
- Do you see many mis-spelled words in the draft body?

There are a few composer performance improvements on our roadmap but it shouldn't be unbearably slow - seems like something else must be up.

**Comment by crxdelsol** [comment]
Hi!

* My reply is just a few lines, < 1000 characters.
* Also occurs when I write a new e-mail *offline* with just a simple HTML signature, and I just start typing random stuff, as when I reply to a conversation with 6 messages already there.
* My testing was completely in my own foreign language without spelling mistakes. (Dutch)

After a few lines I started to notice a little slowdowns in showing up characters which are getting worser and worser after a few more lines of typing. Then it will be too slow and I start making spelling mistakes because I don't see the text appear soon enough.
Then I switch to my IDE (developer job) to type my message and copy+paste the text into the e-mail.

For the record:

**Device:** Retina MacBook Pro late 2014 (model: MacBookPro11,1)
**Display:** Internal MacBook screen: 13,3-inch (2560 x 1600)
**CPU:** 2,6 GHz Intel Core i5
**RAM:** 8 GB 1600 MHz DDR3
**Video:** Intel Iris 1536 MB
**SSD:** APPLE SSD SD0128F
**OS:** 10.11.3 bèta (15D13b) (Also had this before on retail versions of El Capitan)

**Comment by crxdelsol** [comment]
For the record, I also tested this on the latest version:

**0.4.9-575c091 (0.4.9-575c091)**

Some new analysis, this only occurs to a specific e-mail account. Other accounts do not have this issue so far as I have been able to test today.

If I send an e-mail from that account to another one of mine, and from the other I respond to it, also no issue there. It's only directly noticeable after 2 lines of text when I compose in that one specific e-mail account.

**Comment by dennisjanssen** [comment]
Same issue here, on a pretty similar machine (Macbook Pro on latest OSX). Speed varies a lot, so it's not all the time, but at times it's really slow. A few minutes ago, I managed to type 3 full sentences and then had to wait about 30 sec. for everything to appear.

Popping out the external composer isn't really helping, still pretty sluggish while typing.

**Comment by mrelwood** [comment]
First time user, version 0.4.25-a22631a. Same issue, and in my case it is the spell checker. Typing in English is fine, but using my native Finnish typing gets very sluggish after one single sentence.

An option to remove the spell checker completely, please.

**Comment by dennisjanssen** [comment]
@mrelwood That makes a lot of sense, other native language than English here as well. So +1 on that.

**Comment by happylinks** [comment]
Same here, typing dutch makes it really slow.

**Comment by grinich** [comment]
Is this still happening in the latest release?

**Comment by crxdelsol** [comment]
I am currently downloading N1 again. The latest update screwed up my current installation. The splash screen comes up, it starts drawing the main window, and crashes, showing the splash screen again, over and over.

(Video here: https://dl.dropboxusercontent.com/u/7528392/n1-crash.mov)

**Comment by mrelwood** [comment]
It still happens on 0.4.25-a22631a, although perhaps to a slightly lesser
degree.  
  
\- mrelwood.  
![](https://link.nylas.com/open/73e32hbnboil627qej3qtwhmh/local-9b103083-d4f3)

On Apr 27 2016, at 9:44 pm, Michael Grinich &lt;notifications@github.com&gt;
wrote:  

> Is this still happening in the latest release?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1069#issuecomment-215188731)![](https://github.com/notifications/beac
on/AG6Qz4hSF_EZn4LxVPjeq3OFdhYEc4UQks5p765wgaJpZM4HHyCX.gif)

**Comment by happylinks** [comment]
Still happening, can't send dutch emails at all; takes minutes before the typing is "finished".

**Comment by happylinks** [comment]
Also happens when I type in english or just nonsense (asdfasdfasdf).

**Comment by grinich** [comment]
This seems to be occurring when the OS locale is set to non-english and we're running the spell checker.

**Comment by crxdelsol** [comment]
Would it be possible to adjust the spell checker language to the system default?

**Comment by bengotow** [comment]
Hey folks - I've made a few changes in 15ef74e0e2063dce732a7e983d3676a069fbcc6b which should bound the performance cost of the spellchecker (by capping it at finding 15 mis-spellings) and cut down on needless DOM node creation. I think this is still a major issue and we'll look at doing a broader overhaul soon.

**Comment by crxdelsol** [comment]
I just updated to this version:

**0.4.40-85cf726**

It's a bit better now, but still quite a lag after a few sentences.
Perhaps adding an option to disable spell checker completely in N1 settings would be a solution to some.

**Comment by chr-br** [comment]
I have the same issue and it is clear that it is also the spell checker that is the problem: my system language is set to french, typing in french in Nylas is fine, but typing in English creates spelling errors and causes sluggishness. It is better now, but still annoying --- I would certainly like an option to disable the spell-checker, at least as a temporary quick fix.

**Comment by jackiehluo** [comment]
Just added https://github.com/nylas/N1/commit/42e876ab1f99270b003e6ed7bc5e8fe055b1c54c, which should be a temporary fix for the performance issues and the lack of language detection from #1392. We're still looking at real solutions for both!

**Comment by jboykin** [comment]
I have this issue too on Windows 10 Surface Pro 4, it's pretty bad. 
Locale is United States, language is English.

**Comment by emorikawa** [comment]
Additional info on this bug can be found in: https://github.com/nylas/N1/issues/2507 and https://github.com/nylas/N1/issues/1360

**Comment by emorikawa** [comment]
Here's a profiler snapshot from @GM-Polyakov machine. This was captured on a large thread with 43 replies, even when quoted text was collapsed. We're clearly doing something dumb with `parseFromString` causing serious lag on large threads.

![output-profile](https://cloud.githubusercontent.com/assets/489001/16745730/0168490c-476c-11e6-8f94-fad0027a6319.jpg)

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4362

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4077

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4362

**Comment by clifgriffin** [comment]
I can't even get the reply window to open up these days. Takes 10 minutes to show, and then it generates one for every time I clicked. 

I've had to switch to something else for now. Just too slow.

**Comment by jackiehluo** [comment]
Okay, this issue should be at least partly fixed with this commit: https://github.com/nylas/N1/commit/87dba382a8779c95c0a4e975cf5af8cc8a667661

We narrowed down on a serious lag that occurred when you tried responding to long email threads or HTML emails—if your problems were occurring in different circumstances (i.e., replying to a single email that only contained text), let us know!

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!

**Comment by happylinks** [comment]
I still see this issue in version "0.4.47-3a2a94c (0.4.47-3a2a94c)".

**Comment by jackiehluo** [comment]
@happylinks Does it help if you disable spell check in the settings?

**Comment by happylinks** [comment]
@jackiehluo After turning off the spell check and restarting (important) it isn't slow anymore.

**Comment by samgabell** [comment]
Why is this issue still closed? Are you suggesting the fix is to permanently disable spell checker?

**Comment by bnsblue** [comment]
Same question: why is this issue still closed? Have you guys figured out/fixed the performance bug mentioned in @emorikawa's post? I am still experiencing huge lag when the spell check is enabled.

**Comment by grinich** [comment]
@bnsblue Yes, we fixed the lag from the previous issue.

General bugs for things like "slow performance" aren't useful to keep open. They're similar to things like "make the design better" or "make the binary smaller" etc. without specific issues or goals.

If you are still having issues with lag, please open a new issue with info about your system, how the issue is presenting itself, and full detail about what you're typing and how long the draft is. Screencasts are great and reproducible scenarios are best.
