### ISSUE TITLE
Messages matching multiple rules endless loop [mail rules]

### ISSUE THREAD

**Issue by danielbayley** [nylas/N1#1076]
Messages that match more than one rule that moves them into folders get thrown into an endless loop of being moved between those folders. Maybe there should be something to prevent this based on the order of the mail rules?

**Comment by danielbayley** [comment]
One solution might be to have ‘not in folder’ or ’not matching rule’ criteria…

**Comment by bengotow** [comment]
It looks like this is related to a sync-engine issue where moving messages between folders gives them new IDs, and appears as a `delete` + `create` event rather than a `move` event. This causes N1 to run mail rules again.

This should be fixed in the sync engine this week. Stay tuned.

**Comment by danielbayley** [comment]
> It looks like this is related to a sync-engine issue where moving messages between folders gives them new IDs, and appears as a delete + create event rather than a move event. This causes N1 to run mail rules again.

That makes sense, as moving a message manually also tends to mark it as unread, which is another issue. However, criteria like ‘not in folder’ or ’not matching rule’ are still necessary to avoid acting on everything across mailboxes (especially including the trash…)

**Comment by bengotow** [comment]
Hey @danielbayley—hmm, mail rules are designed to process incoming mail which is pretty much always in the Inbox. We actually debated making mail rules /only/ process mail in the inbox. Do you think that'd be an improvement? We don't really intend for people to create advanced processing workflows with the "run on existing mail" feature. (We actually just built it because our mailboxes were overrun in the weeks and months before we built mail rules!)

**Comment by danielbayley** [comment]
> We actually debated making mail rules /only/ process mail in the inbox.

I think that would definitely be an improvement at least.

> (We actually just built it because our mailboxes were overrun in the weeks and months before we built mail rules!)

Probably the same story for most _users_…

**Comment by bengotow** [comment]
We'll be making additional improvements to mail rules in maintenance releases next month. Going to close this ticket, because this specific issue was related to a backend issue that has been resolved.

**Comment by vacantgeologist** [comment]
I am still seeing emails passed around between folders endlessly when more than one rule applies using . Can we be clear about this: if the rules are arrange from top to bottom in a certain order, are they executed in that order? Meaning that if there are rules #1, #2, and #3, and an email is affected by #1, it won't be touched by #2 or #3?
