### ISSUE TITLE
Can't add KolabNow account

### ISSUE THREAD

**Issue by forgottenleaf** [nylas/N1#1288]
I'm trying to add my KolabNow account using the following settings:

From https://kolabnow.com/clients/others
```
Incoming server (IMAP):
imap.kolabnow.com

Port/Security:
993 + SSL

Authentication:
Password

Username:
test@kolabnow.com


Outgoing server (SMTP):
smtp.kolabnow.com

Port/Security:
587 + STARTTLS

Authentication:
Password

Username:
test@kolabnow.com
```

but it just won't work. It says error connecting to the server, and I see an HTTP status code of 404 in the activity window, but no error information. Just to clarify, my email does not end with `@kolabnow.com`.

My setup:

```
Macbook Pro 13" (not retina) Mid 2012
OS X El Capitan 10.11.1
Nylas N1 Version 0.4.5-b0ec335 (0.4.5-b0ec335)
```

**Comment by mbilker** [comment]
Could you post a picture of the Activity Window?

For security, the information presented in the Activity Window is not enough to gain access to your account, but it does allow the Nylas members to find out the issue from their end.

**Comment by forgottenleaf** [comment]
Actually the activity window is showing plaintext email and password, so it is enough to gain access to my account, but here's a screenshot with that info deleted and blacked out.
![screenshot 2016-02-10 21 09 28](https://cloud.githubusercontent.com/assets/3428118/12956897/551a86da-d03b-11e5-8dba-fe5ffd0b2145.png)

**Comment by bengotow** [comment]
Hi @forgottenleaf — this should be fixed now. Turns out it was an issue on our end. Can you try again?

**Comment by wsfulmer** [comment]
Still not working with WebFaction, using credentials that have been verified to be valid.

The error *did* change from "Error connecting to the server" to "Invalid credentials" after @bengotow's last post, but as I said, the credentials are correct.

Here's the curl command from the activity window:

```
curl -X POST -d
'{
  "settings":{
      "imap_port":993,
      "imap_ssl_enabled":true,
      "smtp_port":587,
      "smtp_ssl_enabled":true,
      "imap_host":"mail.webfaction.com",
      "imap_username":"████████",
      "imap_password":"████████",
      "smtp_host":"smtp.webfaction.com",
      "smtp_username":"████████",
      "smtp_password":"████████"
  },
  "name":"Sean",
  "email":"████████@████████.com",
  "provider":"imap"
}'
"https://:@api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=149fa927-43f2-4325-9906-f1218e566e90"
```

**Comment by forgottenleaf** [comment]
@bengotow Yeah, it did work for me. Thanks. Don't know if I should close this since @wsfulmer has an issue but it doesn't seem to be related to KolabNow.

**Comment by logandavis** [comment]
We just deployed a backend update to fix the (second) authentication issue you reported (dupe of #954 and #322). If you continue to have problems authenticating generic IMAP accounts that use IMAP/SMTP-specific credentials, please email support@nylas.com. Thanks!

**Comment by wsfulmer** [comment]
Still not working for WebFaction, back to the "error connecting to the server" message. I'll email you.
