### ISSUE TITLE
Open new message, closed main window, can't get it back.

### ISSUE THREAD

**Issue by elice82** [nylas/N1#1602]
When opening a new message, I closed the main window (viewer window) and I couldn't get it back.
By clicking the dock you don't get the main window back or in the menu bar there is no link to main window.

With Mail for Mac OS X you can get the main window (viewer window) back.

Mac OS X 10.11.3 Nylas N1 Version 0.4.10-4e3595b. No plugins installed.
Using it with Gmail accounts.

**Comment by mbilker** [comment]
Please upgrade to 0.4.16. This should be fixed in the recent version.

**Comment by elice82** [comment]
I tried it but still it doesn't work.

**Comment by sanjeevverma1** [comment]
I'm running the latest 0.4.25 and the issue still persists: open main window, open composer, then close main window. Now, neither clicking/double-clicking on dock icon, nor right-click+Show All Windows will reopen the main window. The issue can be annoying if you use ⌘w and ⌘tab shortcuts often. 

In the meantime, I found two workarounds to reopen the main window:
1. Open Preferences from Menu Bar (⌘,) then click "< Inbox" in top left
2. Close composer window then click dock icon

Neither are great.

**Comment by elice82** [comment]
There's a menubar icon on the right (Mac OS X) where you can open the main window with.
I didn't seen that before.
@sanjeevverma1 Thank you for the other options!

**Comment by KevinMartin** [comment]
If you do ⌘+1, this will also work.

**Comment by elice82** [comment]
@KevinMartin 
I checked it (⌘+1) but it doesn't work when you close the main window and leave the new message in front.

**Comment by KevinMartin** [comment]
Just tested that. You're right.

**Comment by sanjeevverma1** [comment]
One solution would be to add a keyboard shortcut for the "Open Inbox" button under the menubar icon, but this (and many other issues) should be fixed when Nylas switches to the native-OS X interface for application windows.

**Comment by KevinMartin** [comment]
How does this get solved by Nylas switching to the native OS X Interface? The only non-native part of the window are the traffic lights. But that bc Nylas is using `titleBarStyle: 'hidden'` on the `BrowserWindow` class. Toggling that to any other option wouldn't fix this issue.

**Comment by bengotow** [comment]
This should be fixed by 1347654bbf2d1ac8cbbc8225f9bc7cf226481971. Stay tuned!

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!

**Comment by sanjeevverma1** [comment]
Running 0.0.40 on OSX 10.11.5 and the issue still persists. 

Steps to reproduce: 
1. Open N1
2. Open composer window
3. Close main inbox window
4. Click dock icon
**Main inbox window doesn't open**

**Comment by sanjeevverma1** [comment]
But, I did find that you can re-open the main inbox window with the ⌘0 keyboard shortcut
