### ISSUE TITLE
Unable to Snooze (Can't create snooze category)

### ISSUE THREAD

**Issue by 5imple** [nylas/N1#1676]
Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- Are there any related issues?
Nope

- What operating system are you using?
Mac OS 10.11.4

- What version of N1 are you using?
Version 0.4.14-53cd69b (0.4.14-53cd69b)

**Bug?**
- Do you have any third-party plugins installed?
yes default (quick reply & send later) - tried to disable the, restart and try but it didn't work

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I tried it with Gmail only (no other access to try)

- Is the issue reproducible with a particular attachment, message, signature, etc?
with all messages

I updated my N1 client, after that this issue happened (I removed the app, and return to the old version, but the same issue still happening (restart and do the standard troubleshooting, didn't solve it)

screenshot 
![image](https://cloud.githubusercontent.com/assets/17810882/13728663/d2120180-e95a-11e5-9b19-becfce37ab71.png)

**Comment by jstejada** [comment]
Hi @5imple, this is a duplicate of #1556 , however I'm keeping this one open. We are working on a fix for this and will release a patch soon. Does this happen as soon as you open the app, or when you try to snooze?

**Comment by jstejada** [comment]
Oh I saw the logs you posted in #1556 , thanks!

**Comment by 5imple** [comment]
@jstejada -  it will be great if there is a work around to apply until the patch is ready

**Comment by jstejada** [comment]
hey @5imple, yeah. Is this continually happening to you when you open the app? As a workaround, you can log in to Gmail and manually delete the label `N1-Snoozed`

**Comment by 5imple** [comment]
Yes, it continuously happening - after deleting the N1 label, would I lose
my snoozed email?

I mean, the old snoozed email will come on time?

**Comment by jstejada** [comment]
@5imple, thanks. Yes, you'd need to unsnooze them, delete the label, and resnooze them :/ Sorry for the trouble! We should be shipping a fix soon. Can you confirm if you are getting the error message as soon as you open the app, or when you try to snooze?

**Comment by jstejada** [comment]
also, could you open the Activity Window via `Developer -> Open Activity Window` and let me know what the failed request is? Thanks! cc @myovchev

**Comment by jstejada** [comment]
this should be fixed with https://github.com/nylas/N1/commit/cfbbcd23d3f01a22430b4f82f305aa1df68c9428

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Comment by csteinlehner** [comment]
I still having this issue in 0.4.51-93ef779

I tried Nylas a few month back and went away from it. After installing the latest version, I got this error.

**Comment by MidnightLightning** [comment]
I'm also getting this error message when attempting to snooze something, but with an IMAP account, not a GMail one.

**Comment by 5imple** [comment]
I left nylas!

Newton app is stable :)
