### ISSUE TITLE
Menu bar icon becomes completely blue when clicked on

### ISSUE THREAD

**Issue by abhishekbanthia** [nylas/N1#1876]
##### Are there any related issues?

...

##### What operating system are you using?
OSX El Capitan 10.11.4

##### What version of N1 are you using?
 0.4.19-d41e72c

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
N/A

The menu bar icon becomes completely blue when I click on it.

<img width="176" alt="screen shot 2016-04-03 at 2 20 32 pm" src="https://cloud.githubusercontent.com/assets/8280282/14268177/06349782-faa6-11e5-8762-9b8f8858e699.png">

**Comment by jackiehluo** [comment]
Should be fixed now!

**Comment by sanderploegsma** [comment]
I am running Nylas mail 1.0.29 and this is still an issue...
