### ISSUE TITLE
Unable To Unistall

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2117]
##### Are there any related issues?

...

##### What operating system are you using?
10.11.4
...

##### What version of N1 are you using?
0.4.32-1de17e7 (0.4.32-1de17e7)

--

**Bug?**
##### Do you have any third-party plugins installed?
Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?.
No
...

**Comment by oldhickory30** [comment]
Since the bcc and cc problem has not been fixed and I have been unable to  use Nylas for two versions now! However I cannot completly remove it either, the file-  - ~/.nylas does not not exist. Shame, you started out with a client, yet made it unusable!

**Comment by bengotow** [comment]
Hey! Are you sure there are still Nylas-related files on your computer? It may already be entirely deleted if there's no folder at that location.

Also I believe that BCC / CC problem was fixed in this release (`0.4.32`). Cheers!

**Comment by oldhickory30** [comment]
Yes Nylas still resides on my MAC, and yes there is still an issue with bcc and cc, so no it wasn’t fixed!
Not sure why you closed the case.
