### ISSUE TITLE
Custom keybindings don't override existing ones

### ISSUE THREAD

**Issue by laughedelic** [nylas/N1#2134]
After the 0.4.32 upgrade and the change from `.cson` to `.json` format for the custom keybindings, behaviour also has changed. I have Gmail keybindings in the settings. I add for example

```json
  "core:change-category": "c"
```

to my `keymaps.json` and expect than when I press `c` it will open the **c**ategory changing dialog (as it was before when I used `keymaps.cson` with the same keymap). But what happens is that now **both** `application:new-message` and `core:change-category` are mapped to `c` 😐 

It's quite absurd. I know that I can just take the Gmail `keymaps.json` template and override _all_ keymaps _manually_ avoiding conflicts. This is not a solution.

P.S. This update wasn't nice for me at all: it just ruined all my workflow with the keymaps that I'm already used to, offering an empty `keymaps.json` file and even any documentation on how to write new keymaps (thanks, I can search the Github repo) 👎  Was it really hard to offer an automatic conversion of `.cson` to `.json`?

**Comment by bengotow** [comment]
Hey! Sorry for the hassle—setting up custom keybindings wasn't a documented feature so we didn't intend for anyone to have a `keymaps.cson` file, thus no migration path.

I'll see if we can get that overriding behavior fixed in the next release. Cheers!

**Comment by bengotow** [comment]
Hey! I stand corrected - we did document it in the knowledge base. Sorry for the switch up! We're cleaning up tons of code that was left over from when we formed Atom and we'll get some new documentation up soon.

**Comment by laughedelic** [comment]
@bengotow Thank you.
JFYI, v0.4.33 doesn't fix it.

> we did document it in the knowledge base

What is this knowledge base?

**Comment by bengotow** [comment]
This should be resolved in bbdfa85547795d53d41e1d7f1b0e2f18e0888071. You can now click the keybindings to override the defaults an put in your own, directly from the preferences screen. There won't be another public release until next week, but if you want to try it out you can pull down the CI build! https://edgehill.s3.amazonaws.com/0.4.34-bbdfa85%2Fdarwin%2Fx64%2FN1.dmg.

The KnowledgeBase is over here: https://support.nylas.com/hc/en-us/sections/203638587-N1. Cheers!

**Comment by laughedelic** [comment]
@bengotow Wow! That sounds like a nice feature. Sure, I'll try this build 👍

**Comment by laughedelic** [comment]
Here are several things that I noticed so far:

- I couldn't find a way to reset a particular keymap through this interface, only Reset All. If I screwed up, I'd like to be able to cancel that or reset one keymap to default.
- Is there a way to set key to `None` like it is in the Apple Mail keymap set for some of the keys? I tried to set a custom keymap to empty string (in the `.json` file), but I'm not sure it's the same.
- It would be nice to have an empty preset (or "minimal"?) to assign only user-defined keymaps

Other minor things:
- Default keymaps can be lists of keys (alternatives), but there is no way to add several alternatives through the interface (just as a note, for me personally, it's not important)
- If default mapping is to escape, it will be written `Escape`, if it's a manual remap, it will be `Esc`.

Anyway, this is an awesome feature 👍 it really improves usability.

**Comment by laughedelic** [comment]
A glitch: if map (through the interface)
``` 
 "core:change-category": "c",
```

I have to quickly press `c` twice to get the labels dialog. If I map it to any other key, it works fine.

**Comment by laughedelic** [comment]
I see this in the 0.4.37 release 👍 Thanks a lot!
I'm informing that the glitch with <kbd>c</kbd>: mapping is fixed. But the rest of my concerns (https://github.com/nylas/N1/issues/2134#issuecomment-217538671) are still actual. Plus one more minor thing:
- default keymaps list <kbd>cmd</kbd><kbd>shift</kbd>, while use-defined ones, do it another way round: <kbd>shift</kbd><kbd>cmd</kbd>:
  <img width="126" alt="screen shot 2016-05-16 at 00 17 35" src="https://cloud.githubusercontent.com/assets/766656/15277192/0137809c-1afd-11e6-9106-bc3d488bfbd0.png">  
  (here I remapped "Reply All" as an example)

**Comment by jstejada** [comment]
Hey @laughedelic thanks for the feedback! Editing keymaps from preferences has shipped in v0.4.40 and should be hitting the auto updater soon, so I'm going to close this for now. Feel free to reopen or submit a new issue if you have trouble. Thanks!

**Comment by laughedelic** [comment]
Hi @jstejada. I don't see anything related to keymaps in the v0.4.40 release notes. This feature was shipped in v0.4.37 some days ago as I wrote just above you comment: https://github.com/nylas/N1/issues/2134#issuecomment-219314838. The feature works and the initial issue is solved. But there are some little problems with it as described in https://github.com/nylas/N1/issues/2134#issuecomment-217538671. I can open a new issue with those things if you want.
