### ISSUE TITLE
Error thrown during update, message list not showing, errors in console

### ISSUE THREAD

**Issue by jkondratowicz** [nylas/N1#2278]
##### Are there any related issues?

I've found no related issues.

##### What operating system are you using?
Windows 8.1 64bit

##### What version of N1 are you using?
0.4.40

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No.

One of the updates within last few weeks returned an error and all updates since do (most recently - update to 0.4.40), yet the program updates successfully. Error returned:
```
[Window Title]
Nylas N1

[Main Instruction]
Error

[Content]
app-0.4.38 is a directory. Try compressing it and attaching it again.

[Okay]
```

Since that one update took place, one of 3 mailboxes I have connected doesn't work, i.e. it doesn't display message list (constant spinner) both on this account's view and in "shared" inbox. Two other accounts work alright. All three are Gmail accounts. Errors are thrown in console, log is attached.

[nylas.log.txt](https://github.com/nylas/N1/files/274192/nylas.log.txt)

**Comment by bengotow** [comment]
Hey - thanks for reporting this. I believe we've fixed the "app-0.4.38" error in  d2d79c6e2de72dad7054451e8eda35907d0f85f4, but it'd be great to see if it happens the next time you update. Could you try going to Preferences > Accounts and clicking "Re-authenticate with Gmail" for that account? If that doesn't fix it, there may be a few other things we can try!

**Comment by jkondratowicz** [comment]
Hi, thanks for a reply - I tried re-authenticating with Gmail for that account, it didn't help (errors about the unexpected token in a query are still thrown). I then tried removing that account and re-adding it, unfortunately that didn't help either. I don't think it's a problem with that particular account, because I'm having no problem accessing it via Nylas N1 from another computer.

**Comment by jkondratowicz** [comment]
@bengotow I uninstalled Nylas and installed it again from freshly downloaded setup, unfortunately it didn't help. I'm out of options, any ideas? The problem is that I'm still getting errors:

**Comment by jackiehluo** [comment]
Sorry about the long delay—we pushed an update today that allows you to reset N1 in these cases! Going to close this issue for now, but if you have this problem again, let us know.
