### ISSUE TITLE
Missing Nylas ID token stops sync in N1

### ISSUE THREAD

**Issue by jackiehluo** [nylas/N1#2541]
> Hi guys! After I upgraded to Nylas Pro with you free coupon code, my email accounts don't work anymore :/ Developer tools' console gets me this error : "APIError: Identity is present but identity token is missing."Can you help me? Thanks!

>Thanks for your reply.
I'm on Ubuntu 16.04 and I deleted .nylas folder in my home folder but nothing changed. I can also reinstall the app but it still doesn't work. After signing in with Gmail, the app quits (I don't think it's the correct behaviour) and then when I restart N1, the console gets me always the same error.
Hoping it could be helpful, another displayed error is "Unable to refresh IdentityStore status: auth() received invalid user or password". I tried on a Mac and it works! So there is something strange in my Ubuntu but I can't understand what :(

**Comment by inceptorus** [comment]
I have the same issue on Ubuntu 16.04. The issue is not specific to Gmail, as it happens to me when I try to connect to Exchange.

**Comment by audibleblink** [comment]
Same here when trying to Trash a message on Gmail.

```
ChangeLabelsTask (ID: 5708) FAILED (PROCESSING REMOTE) APIError 400 Identity is present but identity token is missing.
```

Can otherwise receive and read email normally

**Comment by bengotow** [comment]
Hey folks! We pushed a small fix yesterday (329ea706709401b8ca810b4008f0fc5940ce9bf8
) which shows an error when N1 is unable to save the identity token to your system keychain—I believe that's causing the problem (maybe gnome-keytar is missing?). That should make this an actionable issue.

**Comment by tyrbo** [comment]
`/usr/share/nylas/resources/app.asar/src/flux/stores/identity-store.js:68 Unable to refresh IdentityStore status: auth() received invalid user or password`

Seem to have identity token issues still. Arch Linux with 0.4.47.

All I've done is install Nylas and attempt to add my Gmail account, which succeeded, but I was then greeted with the empty Inbox (with no accounts listed on the sidebar) and that error in the console.

**Comment by chauncey** [comment]
I'm also on Arch and had the same issue. Exchange and Gmail showed empty. I narrowed down my issue to the ~/.local/share/keyrings folder. I have a new Arch install that just worked so I checked my keyring. I used seahorse for this and noticed on the new install, I had a Password Keyring with Nylas entries. On my work Arch install, I didn't have these keys. I don't really rely on gnome-keyring for anything so I removed everything and started fresh. 

I backed up the keyrings folder, and removed the ~/.nylas folder and ~/.local/share/keyrings folder to start fresh. I then created a new keyrings folder and used seahorse to create a new default keyring. Went through N1 setup including the Nylas account, my work Exchange account and gmail account. After a slight delay all of my email came in.

Looking back it's more than likely it was originally a permissions issue, but I can't say for sure.

**Comment by jarias** [comment]
I found the issue might be in the implementation of `node-keytar`, currently it uses `libgnome-keyring` which is mark as deprecated, I extracted the C++ code and test as standalone and and I get `Error communicating with gnome-keyring-daemon` which is actually swallowed by `node-keytar` that's why N1 can't give a proper error message of what is going on, I don't know the exact reason by this error is happening, maybe something change in `gnome-keyring` that makes `libgnome-kering` no longer usable or could be dbus issue, in any case if I change the same code to use `libsecret` witch is the prefer form to communicate with `gnome-keyring` now it works fine.

Another test I did was to use `node-keytar` directly and it didn't work.

I'm going to work on a PR to `node-keytar` to update the Linux impl to use `libsecret` and see if upstream accepts it.

Ref code:

https://github.com/atom/node-keytar/blob/master/src/keytar_posix.cc

Deprecation notice of `libgnome-keyring` https://mail.gnome.org/archives/commits-list/2014-January/msg01585.html

**Comment by jstejada** [comment]
@jarias thanks a lot for tracking that down! Let us know if that PR gets merger. I'm referencing issue #2771 which involves adding better messaging to missing. Also, people running into this might find the discussion in #2062 useful, which suggests installing `gnome-keyring` and `libgcrypt20-dev`

**Comment by gmorenz** [comment]
Looks like [an equivalent](https://github.com/atom/node-keytar/pull/63) PR was finally merged 👍

**Comment by johnramsden** [comment]
So this should mean that Nylas will finally work properly with KDE? We no longer have to install gnome keyring? 

For us KDE users it's really frustrating having to install gnome keyring just for one application.
