### ISSUE TITLE
Programing Panel Appear

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2666]
##### Are there any related issues?

...

##### What operating system are you using?
...OSX 10.11.6

##### What version of N1 are you using?
...0.4.45-7637265)
--

**Bug?**
##### Do you have any third-party plugins installed?
Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
 No
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
...
![panelerror](https://cloud.githubusercontent.com/assets/16170272/17076402/d8a8d206-506d-11e6-96f5-8cb985b0b218.jpg)

**Comment by oldhickory30** [comment]
This panel appears frequently for no reason, very frustrating.

**Comment by grinich** [comment]
Which third party plugins do you have installed?

**Comment by oldhickory30** [comment]
Several themes and
unsubscribe.![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
639ef4c5-197d?r=cmVwbHkrMDBmNmJkMjBkNDMwNWZlOWQ1NjM1OWMzMDRkY2VkNTVhZTY2Mzg4ZTI1OGE4ZmVhOTJjZjAwMDAwMDAxMTNhYjhmOTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 23 2016, at 2:03 pm, Michael Grinich &lt;notifications@github.com&gt;
wrote:  

> Which third party plugins do you have installed?

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2666#issuecomment-234737330&r=cmVwbHkrMDBmNmJkMjBkNDMwNWZlOWQ1NjM1OWMzMDRkY2VkNTVhZTY2Mzg4ZTI1OGE4ZmVhOTJjZjAwMDAwMDAxMTNhYjhmOTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe-
auth/APa9IBClp_kaDId9KQgQUEGzg3HrSpKhks5qYnOTgaJpZM4JTTKg&r=cmVwbHkrMDBmNmJkMjBkNDMwNWZlOWQ1NjM1OWMzMDRkY2VkNTVhZTY2Mzg4ZTI1OGE4ZmVhOTJjZjAwMDAwMDAxMTNhYjhmOTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/APa9IH_lHNtSQ984ugwAUumGE-MddZkDks5qYnOTgaJpZM4JTTKg.gif)

**Comment by jackiehluo** [comment]
@oldhickory30 Which error do you see if you click "Console"? When does the window open?

**Comment by oldhickory30** [comment]
/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/rx-
lite/rx.lite.js:81 Uncaught TypeError: Cannot read property 'usesLabels' of
undefined  
![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
7e8dd7c5-8d80?r=cmVwbHkrMDBmNmJkMjAxNDIxMzE2MDVlNDc0MjJlOTBiNWQzNDViZTY2MTU0YTcxZjE5MmU2OTJjZjAwMDAwMDAxMTNhZDU3ZTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 24 2016, at 10:30 pm, Jackie Luo &lt;notifications@github.com&gt;
wrote:  

>
[@oldhickory30](https://github.com/oldhickory30&r=cmVwbHkrMDBmNmJkMjAxNDIxMzE2MDVlNDc0MjJlOTBiNWQzNDViZTY2MTU0YTcxZjE5MmU2OTJjZjAwMDAwMDAxMTNhZDU3ZTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=)
Which error do you see if you click "Console"? When does the window open?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2666#issuecomment-234834893&r=cmVwbHkrMDBmNmJkMjAxNDIxMzE2MDVlNDc0MjJlOTBiNWQzNDViZTY2MTU0YTcxZjE5MmU2OTJjZjAwMDAwMDAxMTNhZDU3ZTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe-auth
/APa9IOoJtgEU4MJ-Hkp4uFmfmtdZ-
ZlBks5qZDvjgaJpZM4JTTKg&r=cmVwbHkrMDBmNmJkMjAxNDIxMzE2MDVlNDc0MjJlOTBiNWQzNDViZTY2MTU0YTcxZjE5MmU2OTJjZjAwMDAwMDAxMTNhZDU3ZTM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9IJ1c
--BYe-cReUF4K8anD5Xc-kW_ks5qZDvjgaJpZM4JTTKg.gif)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. It should be fixed in 0.4.47—can you try upgrading?  If it happens again, please press "Esc" while in the side panel and it'll show the console where you can see the error in full. If you could post the entire error message, I'll re-open :-)

**Comment by oldhickory30** [comment]
Nope, not fixed, still appears!  
  
Sent from [Nylas
N1](https://nylas.com/n1?ref=n1&r=cmVwbHkrMDBmNmJkMjA3ODVlM2RjNDk1MDM1ZDRlYTZmYmYxNjFiZTE1YmFlMjM1ZGQ0MzNiOTJjZjAwMDAwMDAxMTNiMjY5ZDM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail
client.![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
9e35d468-3586?r=cmVwbHkrMDBmNmJkMjA3ODVlM2RjNDk1MDM1ZDRlYTZmYmYxNjFiZTE1YmFlMjM1ZGQ0MzNiOTJjZjAwMDAwMDAxMTNiMjY5ZDM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=)

  
On Jul 28 2016, at 6:48 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Closed
[#2666](https://github.com/nylas/N1/issues/2666&r=cmVwbHkrMDBmNmJkMjA3ODVlM2RjNDk1MDM1ZDRlYTZmYmYxNjFiZTE1YmFlMjM1ZGQ0MzNiOTJjZjAwMDAwMDAxMTNiMjY5ZDM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=).

>

> --  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2666#event-738635570&r=cmVwbHkrMDBmNmJkMjA3ODVlM2RjNDk1MDM1ZDRlYTZmYmYxNjFiZTE1YmFlMjM1ZGQ0MzNiOTJjZjAwMDAwMDAxMTNiMjY5ZDM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe-
auth/APa9IBbZGpMwgNTVBH7rwA86DCQFbf3Oks5qaU3TgaJpZM4JTTKg&r=cmVwbHkrMDBmNmJkMjA3ODVlM2RjNDk1MDM1ZDRlYTZmYmYxNjFiZTE1YmFlMjM1ZGQ0MzNiOTJjZjAwMDAwMDAxMTNiMjY5ZDM5MmExNjljZTA5ZjZkNDM3QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9IMHpGJBMC55yjCxcYoEaD0caf9T9ks5qaU3TgaJpZM4JTTKg.gif)
