### ISSUE TITLE
Messages won't print

### ISSUE THREAD

**Issue by Pete5x5** [nylas/N1#2832]
##### Steps to reproduce:
1. Open message
2. Click printer icon near top-right of message
3. A window opens with a print preview.  Click the blue Print button in the top-right corner.
4. System printer dialog opens.  Make sure correct printer is selected.  Click print.

##### Expected result: 
Message is printed.

##### Actual result:
Message is not printed.  Nothing shows up in the print queue.  Doesn't seem like anything was sent to the printer at all.

##### Additional Notes:
Printer is working fine.  If I open the same message in the gmail web client and try to print it works fine.  Tried numerous other programs and everything is printing fine.

##### Are there any related issues?

...No

##### What operating system are you using?
...Issue found on both windows 7 Pro and Windows 8 Pro

##### What version of N1 are you using?
...0.4.51

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...All messages

**Comment by emorikawa** [comment]
@Pete5x5 yes this is https://github.com/electron/electron/issues/2627 you're seeing here. It was fixed https://github.com/electron/electron/pull/2677. We'll get the fix the next time we upgrade Electron.

**Comment by bengotow** [comment]
Hey folks—this has been resolved in `0.4.56` which was just released this morning. Cheers!

**Comment by hugoalmeidad2r** [comment]
Hey guys, I am running Nylas on version 2.0.32 and this is not solved yet. Any idea if it was solved earlier and the situation reverted because of an electron update or something? Really need to print some email :( 
I am a developer too so let me know if I can help ;)
