### ISSUE TITLE
Design issue with Gmail account icon when png with transparency

### ISSUE THREAD

**Issue by rspt** [nylas/N1#289]
Example of the problem:
<img width="223" alt="screen shot 2015-10-30 at 00 28 09" src="https://cloud.githubusercontent.com/assets/3854017/10834838/2637dfba-7e9d-11e5-822f-38829644300a.png">

**Comment by grinich** [comment]
This should be fixed now. Please re-open if you have steps to reproduce.

**Comment by rspt** [comment]
Thanks! :)

**Comment by forrestbaer** [comment]
I am still experiencing this issue : Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)

Also where is this icon being pulled from?

**Comment by elgandoz** [comment]
I would like to know where the icons are pulled from as well. I have two Gmail and a Google App account and I can see the picture of only one of them.
![screen shot 2016-01-30 at 11 21 17 pm](https://cloud.githubusercontent.com/assets/5859926/12696150/175ca2d6-c7aa-11e5-9830-fc1876c2031a.png)
