### ISSUE TITLE
Typing on the search bar severely slows down N1

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#3001]
This is due to full table scans done on the Contacts table when typing on the search input for the typeahead results, and the fact that DB queries are now synchronous, which blocks the renderer process

**Comment by jstejada** [comment]
incidence here: https://nylas.zendesk.com/agent/tickets/6923

**Comment by jstejada** [comment]
another incidence from @GM-Polyakov

**Comment by GM-Polyakov** [comment]
consistently crashes for certain search strings

**Comment by bengotow** [comment]
Does this crash the renderer process (force a refresh of the N1 window) or totally kill the app? Are there any stack traces? It's one thing for expensive queries to cause jank but they definitely shouldn't be crashing the app...

**Comment by jstejada** [comment]
It doesn't actually crash, it just blocks the process for a very long time and prompts this dialog:

![pasted image at 2016_10_31 12_43 pm](https://cloud.githubusercontent.com/assets/1271509/19897027/b22b174c-a013-11e6-9fb7-67a84f328f36.png)

**Comment by willingc** [comment]
I'm seeing similar behavior when doing a search with N1 on OS X 10.11.6. Seems to have started in the past day or two. Worked just fine prior to that.

- I've tried leaving it for a long time and keep waiting. Doesn't respond though the pop up clears.
- The menu items are accessible but do not function if clicked ('File->Close', Developer menu items)

<img width="939" alt="screen shot 2016-11-01 at 10 28 01" src="https://cloud.githubusercontent.com/assets/2680980/19899887/e7b585f4-a01e-11e6-9436-2cc75a71ecef.png">

**Comment by danielbayley** [comment]
+1. Searching just crashed N1 for me… I have to say search is generally terrible; to the point where I have to open Apple Mail if I want to actually search for an email!

**Comment by jstejada** [comment]
thanks for reporting @danielbayley. Does N1 completely crash, or does it get stuck like in @willingc's example.

Thanks!

**Comment by willingc** [comment]
@jstejada I tried running with Debug selected under the Developer menu. The app gets stuck. No output visible in the developer tools. Does not get to the point of the pop-up.

**Comment by willingc** [comment]
A bit more detail...

Running a search on only one mail account seems to work. Display in console:

<img width="557" alt="screen shot 2016-11-01 at 12 29 53" src="https://cloud.githubusercontent.com/assets/2680980/19904381/9ffed934-a02f-11e6-9fa7-e173611b5522.png">

Running search on Inbox (multiple mail accounts) results in runaway log errors in console:

<img width="552" alt="screen shot 2016-11-01 at 12 30 37" src="https://cloud.githubusercontent.com/assets/2680980/19904442/dbb473d0-a02f-11e6-82ea-da8783ebbaed.png">

Console after popup warning displays:

<img width="1086" alt="screen shot 2016-11-01 at 12 31 23" src="https://cloud.githubusercontent.com/assets/2680980/19904482/05e146ba-a030-11e6-8f19-00ad3158c715.png">

**Comment by flyingclimber** [comment]
Just had this happen to me as well. Had to restart. Nothing out of the norm in the activity window.

**Comment by jstejada** [comment]
this should be fixed in https://github.com/nylas/N1/commit/f55d9962eabd0c03bfe35c917dddebb007032837#diff-07549fe21d662401372c62ccc5ce2f50R233

**Comment by jstejada** [comment]
We've released version 0.4.201 which contains a fix for this. Please let us know if you have any other problems. Thanks!

**Comment by csampersand** [comment]
Still happening for me in 0.4.201

**Comment by willingc** [comment]
@jstejada Just got a chance to test the new release. You may want to reopen this issue as I'm still seeing errors similar to those mentioned by @csampersand. Oddly, it does not seem to do it on all phrases in the same way:
- a search for 'systers' seems to search correctly but the spinning progress icon in the search bar keeps spinning.
- a search for 'fernando' freezes the ui and emits errors as seen by @csampersand.

Here are a few screenshots that may help in debugging.

On startup:
<img width="551" alt="screen shot 2016-11-04 at 02 32 48" src="https://cloud.githubusercontent.com/assets/2680980/20001386/2f92636c-a239-11e6-99e9-3fb8adbe2096.png">

During 'systers' search
<img width="537" alt="screen shot 2016-11-04 at 02 33 43" src="https://cloud.githubusercontent.com/assets/2680980/20001391/2fc46b50-a239-11e6-84ff-b55266246597.png">

<img width="545" alt="screen shot 2016-11-04 at 02 34 08" src="https://cloud.githubusercontent.com/assets/2680980/20001389/2fbf462a-a239-11e6-896f-02f76cf271db.png">

During 'fernando' search (*Note different warnings than when searching for 'systers'*)
<img width="545" alt="screen shot 2016-11-04 at 02 35 47" src="https://cloud.githubusercontent.com/assets/2680980/20001390/2fc473d4-a239-11e6-8abc-709b02d16ca9.png">

<img width="827" alt="screen shot 2016-11-04 at 02 40 43" src="https://cloud.githubusercontent.com/assets/2680980/20001392/2fc5976e-a239-11e6-99f1-5b81fad0c032.png">

<img width="564" alt="screen shot 2016-11-04 at 02 41 38" src="https://cloud.githubusercontent.com/assets/2680980/20001393/2fca0ca4-a239-11e6-9e4c-50c6dfb6cad6.png">

**Comment by willingc** [comment]
@jstejada Tested a few more things. If I search when "Inbox" is highlighted, that is when the above happens. Search appears to work great when an individual mailbox is selected before the search. Possibly related to Subscription, maybe?


<img width="116" alt="screen shot 2016-11-04 at 03 01 25" src="https://cloud.githubusercontent.com/assets/2680980/20001887/5626fae0-a23b-11e6-9277-e785eb3300e5.png">

**Comment by jstejada** [comment]
Hi @willingc, thanks for the additional details! Reopening this issue

**Comment by jstejada** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/7003

**Comment by nielsvr** [comment]
I can replicate the issue. When searching for mail in Nylas the application gets slow and eventually the only way to resume is completely quit Nylas and restart. Searching gets impossible with Nylas.

**Comment by nielsvr** [comment]
Attached a screenshot from the dev tools. The number left is growing bij 100+ a second 

![schermafbeelding 2016-11-07 om 21 17 43](https://cloud.githubusercontent.com/assets/122342/20074250/c3773064-a52f-11e6-81a0-21ef0457a922.png)

**Comment by jstejada** [comment]
Hi folks! A fix for this has just been released with version 0.4.203. Please let me know if you continue having problems. Thanks for your patience!

**Comment by willingc** [comment]
Thanks @jstejada and Nylas team! Tested the latest release from today. Works for individual mailbox as well as consolidated inbox search. Just an FYI the spinning indicator in the search bar will run a while for a large number of emails. With patience the spinning indicator does finish. 

Great job on getting this fixed so quickly. Thanks 💐 :cake:
