### ISSUE TITLE
mailto: links do not open new composer on Linux

### ISSUE THREAD

**Issue by g105b** [nylas/N1#403]
I click a `mailto:` link within a webpage in Chrome, and N1 opens, but there is no new window for composing an email.

**Comment by grinich** [comment]
Thanks for the report! We'll check it out.

**Comment by mbilker** [comment]
When you do that, what are the arguments of the main N1 process in the process manager. It could give some insight on how to detect a clicked email link.

**Comment by g105b** [comment]
There seem to be multiple processes spawned by clicking the mailto link, here's the output of `ps -fp` for each process:

```
for process_id in `pidof nylas`; do
> ps -fp $process_id
> done
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19970 19794  3 22:02 ?        00:00:02 /usr/share/nylas/nylas --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-im
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19928 19794  3 22:02 ?        00:00:03 /usr/share/nylas/nylas --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-im
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19833 19794  3 22:02 ?        00:00:03 /usr/share/nylas/nylas --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-im
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19829 19794  6 22:02 ?        00:00:05 /usr/share/nylas/nylas --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-im
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19816 19790  0 22:02 ?        00:00:00 /usr/share/nylas/nylas --type=gpu-process --channel=19790.0.1123018158 --no-sandbox --supports-dual-gpus=false --gpu-driver
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19794 19790  0 22:02 ?        00:00:00 /usr/share/nylas/nylas --type=zygote --no-sandbox
UID        PID  PPID  C STIME TTY          TIME CMD
g105b    19790  1509  2 22:02 ?        00:00:02 /usr/share/nylas/nylas mailto:test@test.com
```

**Comment by mbilker** [comment]
Ok the last one is the most important. I see the browser launched N1 with the first argument being the address.

**Comment by mbilker** [comment]
@grinich N1 needs to check for a mailto in `process.argv` and open a compose window.

**Comment by mbilker** [comment]
Though, which email would be selected if the user has multiple accounts.

**Comment by ChristopheLux** [comment]
Maybe the primary/main account otherwise put the focus on the choice of email identity to send with...

**Comment by mbilker** [comment]
I am wondering if account/alias selection in the composer window would be easier.

**Comment by bashok001** [comment]
Any update on this, team Nylas?

**Comment by bengotow** [comment]
This should be fixed by b515a5e0e26f96e42bc3efd6ebd948f029f3f5de. I believe this was related to a bug where mailto:// links would only work if N1 was already running.

**Comment by g105b** [comment]
@bengotow if N1 wasn't running, nothing would happen. If N1 was running, it would focus the N1 main window, but a compose window would not appear.

**Comment by bengotow** [comment]
Hey! This should be fixd in `0.4.19`. Can you grab the update and let me know if you still run into the issue?

**Comment by JohnSandel** [comment]
Works like a charm on OS 10.10.5: with N1 set as the default email client, in
the 3 browsers I use daily:

  

  1. Chrome 49.0.2623.87 (64-bit): CMD+SHIFT+i  foregrounds a new N1 message window, populated thus:

  * From field with my default sending addy
  * Subject field with a useful description of the page
  * A live link in the message body
  * A cursor blinking in the To field

  

2\. Firefox 45.0.1: "File &gt; Email link…" [does same].

  

3\. Safari 9.0.3 (10601.4.4) [does same]—but also calls the N1 viewer, so the
windows appear:

  

  * N1 new message window foreground
  * N1 viewer behind that
  * Safari page behind that

(In this instance, it's simple to send the email, which makes the message
window go away, then just click on the Safari window to foreground it; adds a
step, but it's not onerous.)

  

Yay!

  

I'm having trouble updating N1 on my Linux box (Elementary OS 0.3.2, 64-bit,
over Ubuntu 14.04). Elementary's Software Updater (GUI app) only knows about
N1 0.4.16-8cb7748.

  

I was able to download &amp; extract N1 0.4.19 from GitHub, but I don't know
how/where to install all the folders.

  

Can you tell me the command line to grab the latest N1 build via a terminal?
Then I can report on this feature in this Linux distro.

  

Thanks ion advance!

  

\--

John Sandel

  

![](https://link.nylas.com/open/1agfhyvv7m51i6j1eeof12ha1/fa6ff0a244ff497eb853
a63a7ab8ec24)

On Mar 25 2016, at 4:45 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey! This should be fixd in `0.4.19`. Can you grab the update and let me
know if you still run into the issue?

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/403#issuecomment-201591713)![](https://github.com/notifications/beaco
n/APe7rSedGj9qMIQ2Y92WdHA9qXsqGh8vks5pxHOGgaJpZM4Gh3lu.gif)

**Comment by twonth** [comment]
I'm not the OP, but I (still) have this issue. Opening a mailto link in Chrome switches focus to Nylas, but doesn't open a compose window. I'm on Ubuntu 15.04 (Gnome), running Nylas 0.4.19-d41e72c.

**Comment by g105b** [comment]
I can confirm this bug is still open.

Here is a screen recording of the bug in action, using the latest version 0.4.16 in Ubuntu.

https://www.youtube.com/watch?v=OzOl9eneTdQ

**Comment by bengotow** [comment]
Hey folks! We've fixed two separate issues related to mailto links. First, in 0.4.19 we fixed a problem where N1 would launch, but not open a composer when you clicked a mailto link.

In the next release, were fixing a separate issue where mailto links within N1 would open the default mail client when it was not N1. In the next release (due this week) clicking mailto links inside N1 will always keep you in N1.

I believe there may be a third issue, where N1 is not responding to mailto links properly on Linux. Could you do me a favor and try 0.4.19 and see if your issue persists? Cheers!

**Comment by bashok001** [comment]
On Linux with 0.4.19, clicking on mailto: link is launching N1 if not open, would bring N1 to focus if it is open. But as you mentioned, no composer yet.

**Comment by orschiro** [comment]
Dear Ben,

  

I would love to help testing 0.4.19.

  

Thank you very much for your work!

  

Is there any chance I can install this version using an Ubuntu deb package?

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 5 2016, at 7:46 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey folks! We've fixed two separate issues related to mailto links. First,
in 0.4.19 we fixed a problem where N1 would launch, but not open a composer
when you clicked a mailto link.

>

> In the next release, were fixing a separate issue where mailto links within
N1 would open the default mail client when it was not N1. In the next release
(due this week) clicking mailto links inside N1 will always keep you in N1.

>

> I believe there may be a third issue, where N1 is not responding to mailto
links properly on Linux. Could you do me a favor and try 0.4.19 and see if
your issue persists? Cheers!

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/403#issuecomment-205916371)![](https://github.com/notifications/beaco
n/AAKbwz-UQs6b-5KP0mtlsKUGlJXsZQHQks5p0p_igaJpZM4Gh3lu.gif)

**Comment by bengotow** [comment]
Hey folks—This should be fixed in version 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

**Comment by twonth** [comment]
Thanks for your work on this. However, I'm still having the same issue I noted above, despite upgrading to 0.4.25. mailto links switch the focus to Nylas, but don't open a compose window.

**Comment by kungpaogao** [comment]
I am also experiencing the same performance as before. As twonth commented, links just focus Nylas, but don't actually open the compose window.

(Xubuntu 15.10)

**Comment by orschiro** [comment]
Hi all,

  

I can confirm that on Ubuntu 15.10 and Nylas N1 0.4.25 clicking on a mailto
link only gives focus to the main window but does not open a compose window.

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 13 2016, at 4:05 am, kungpaogao &lt;notifications@github.com&gt; wrote:  

> I am also experiencing the same performance as before. As twonth commented,
links just focus Nylas, but don't actually open the compose window.

>

> (Xubuntu 15.10)

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/403#issuecomment-209192965)![](https://github.com/notifications/beaco
n/AAKbw09W2g5xn6sH3EhtvcjRzF0oR9V4ks5p3E9LgaJpZM4Gh3lu.gif)

**Comment by JohnSandel** [comment]
Same here, on Ubuntu 14.04, N1 0.4.25-a22631a.  

  

\--

John Sandel

  

On Apr 13 2016, at 5:27 am, Robert Orzanna &lt;notifications@github.com&gt;
wrote:  

> Hi all,  
  
  
  
I can confirm that on Ubuntu 15.10 and Nylas N1 0.4.25 clicking on a mailto  
link only gives focus to the main window but does not open a compose window.  
  
  
  
Warmly,  
  
  
  
~Robert  
  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source  
mail client.  
  
On Apr 13 2016, at 4:05 am, kungpaogao
&amp;lt;notifications@github.com&amp;gt; wrote:  
  
&gt; I am also experiencing the same performance as before. As twonth
commented,  
links just focus Nylas, but don't actually open the compose window.  
  
&gt;  
  
&gt; (Xubuntu 15.10)  
  
&gt;  
  
&gt; —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N  
1/issues/403#issuecomment-209192965)![](https://github.com/notifications/beaco  
n/AAKbw09W2g5xn6sH3EhtvcjRzF0oR9V4ks5p3E9LgaJpZM4Gh3lu.gif)  
  

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/403#issuecomment-209405105)![](https://github.com/notifications/beaco
n/APe7rZluwfJLrSSDU2pbiBRxihZpqjkfks5p3OEwgaJpZM4Gh3lu.gif)

**Comment by truckingsim** [comment]
Still not working for me on Ubuntu 14.04, N1 0.4.25-a22631a either.

**Comment by albflo** [comment]
Also on Ubuntu 16.04 the bug still exists with version 0.4.25-a22631a.

**Comment by albflo** [comment]
Still not working after Update to 0.4.32-1de17e7 on Ubuntu 16.04.

**Comment by orschiro** [comment]
> Still not working after Update to 0.4.32-1de17e7 on Ubuntu 16.04.

Unfortunately I must agree on this.

~Robert

**Comment by bashok001** [comment]
Since its not working, can we reopen this, @bengotow ?

**Comment by bengotow** [comment]
Hey folks—definitely.

**Comment by orschiro** [comment]
I just clicked on a mailto link in an email and it did open a new window. 

Great, this one is working! :+1:

**Comment by g105b** [comment]
@orschiro which Distro, and what version of N1 and the Distro are you running? Problem still persists on Ubuntu 16.04 with the latest available through the deb.

**Comment by albflo** [comment]
Yes the problem still exists on Ubuntu 16.04 with version 0.4.33-e8f137e.

**Comment by orschiro** [comment]
@g105b Ubuntu 16.04 and N1 0.4.33.

See this screencast: https://cloudup.com/cjg5xeXw1JA

**Comment by twonth** [comment]
Thanks @orschiro . This screencast shows that mailto links work *if clicked on from within a message in N1*. That feature is also working for me. But mailto links from Chrome (for example) still have the issue described at the start of this thread; N1 is brought to focus, but no compose window is opened. Do you agree?

**Comment by orschiro** [comment]
@twonth,

Yes, you're absolutely right! 

It does work from **within** N1 but not from outside N1.

Thanks for clarifying,

~Robert

**Comment by JeroenBoersma** [comment]
My Nylas does shows activity in the taskbar that its triggered, but no new compose window.
Hope this will be fixed soon.

**Comment by JeroenBoersma** [comment]
Looks like it is resolved since the last update... Works on my machine. Ubuntu 14.04 LTS
[v 0.4.38-27d21d1](https://github.com/nylas/N1/releases/tag/0.4.38)

**Comment by grinich** [comment]
@orschiro can you confirm this is fixed?

**Comment by orschiro** [comment]
@grinich, indeed fixed. 

Thank you so much! :smiley: 

~Robert

**Comment by grinich** [comment]
Great!

**Comment by j-rahman** [comment]
@grinich The bug still exists on Xubuntu 16.04 (LTS). I can confirm this. Please reopen.
