### ISSUE TITLE
Feature Request: Stay running while closed on Win, Linux

### ISSUE THREAD

**Issue by IgorKvasn** [nylas/N1#475]
Hi,
I am experiencing some difficulties with tray icon (tested on Linux as well as Windows).
When I close a window I would expect, the N1 would minimize itself to tray (I guess that is the point of having a tray functionality). At first the N1 actually minimizes to tray, but after a while (a few seconds) the N1 process is either killed (this happens on Linux) or the process keeps running in the background, but no tray icon is shown (on Windows).

I am running version 0.3.23 and I have a Gmail account linked to N1.

btw. I am actually not sure, if minimize-to-tray feature is actually implemented - in that case I have a feature request ;)

**Comment by mbilker** [comment]
Not actually implemented. Also, upgrade to 0.3.25.

**Comment by bengotow** [comment]
Hey @IgorKvasn — this is definitely the way it /should/ work, and we'll get it fixed in an update soon. Right now, if you close the main window of the app on Windows or Linux, the app quits. It should really stick around and wait to be quit from the tray menu.

**Comment by IgorKvasn** [comment]
Hi,
I've upgraded to 0.3.27 and it still does not work (tested on Windows - I will try it on linux and let you know it it works there).
The whole Nylas process is killed when I close N1.

**Comment by sreevisakh** [comment]
+1
