### ISSUE TITLE
Inbox (1) and don't know where is that unread email - may be the counter is broken?

### ISSUE THREAD

**Issue by notsu** [nylas/N1#595]
![screen shot 2558-12-07 at 12 37 28 pm](https://cloud.githubusercontent.com/assets/356022/11619928/da544cf8-9cdf-11e5-8f29-e3f809ac80f1.png)

I have been founded this problem two days ago. I don't know where is a "1" unread email (and yes, I can't sleep lol). I already checked in my Gmail account and it's doesn't have any unread email. So, I think the problem might be happened in the application (Something like badge counter?) and I try to scroll to find out where the unread email is, and I can't found it.

Hope you will help me out from unread email nightmare lol. And sorry for my bad English.

**Comment by enoversum** [comment]
Had the same thing at work today. Home installation is fine. I could confirm through another e-mail client that there was actually no unread mail in my inbox.

**Comment by harismahmood89** [comment]
Same here!

**Comment by bengotow** [comment]
Hey folks—sorry this has taken a while to get out. It was fixed on master earlier this week and will be in the `0.3.29` release when it hits the auto-updaters later tonight. Enjoy! Just waiting for the Travis build to complete now...

**Comment by framerate** [comment]
@bengotow I know this has been haunting you guys, but I'm still seeing it and I don't see an open issue for it...

Any suggestions?

<img width="706" alt="screen shot 2016-03-02 at 11 09 14 am" src="https://cloud.githubusercontent.com/assets/74291/13471848/3b751858-e067-11e5-81b7-b6d9102aec67.png">

**Comment by framerate** [comment]
Edit: Looks like this is the current issue, dupe of a dupe of a dupe for anyone else who ends up here:

https://github.com/nylas/N1/issues/759
