### ISSUE TITLE
N1 doesn't open a new tab in Firefox to sign into a Gmail account

### ISSUE THREAD

**Issue by danielvoicu** [nylas/N1#620]
__OS:__ Windows 8.1
__Browser:__ Firefox 42.0
__N1 version:__ 0.3.28

Hi. I've just downloaded N1 and I wanted to add my Gmail account to it, but it seems to get stuck in the sign in process if I already have Firefox open. It works only if the browser is closed.

I'm thinking this might be due to the fact that I no longer have Google Chrome installed. N1 usually opened up a new Chrome tab to sign into that Gmail account.  I've set up Firefox as my default browser, and now N1 stops at "_Sign in to Gmail in your browser_" and hangs there waiting for me to sign into my account.

**Comment by mbilker** [comment]
I wonder if it's because Firefox won't open if there is another instance already open. Chrome I know will open an IPC connection and tell the main Chrome process to open a new tab with the URL. I do not know if Firefox does the same.

**Comment by danielvoicu** [comment]
That's probably it, as Firefox doesn't allow you to run multiple browser instances at the same time. I don't know if this is possible, but maybe N1 could check which is the default browser, and if it's Firefox, it could open a new tab instead of a new window.

**Comment by grinich** [comment]
Might have some more info here: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options

**Comment by roramirez** [comment]
I think is related with #1716

I my test case,with a Firefox 45.0.1 on Linux, when i open a link into the email this not open into a tab in Firefox. Is created the process but no return. 

```{r, engine='zsh', count_lines}
$ ps aux | grep firefox
rodrigo   8518  2.9  4.8 1472536 396632 ?      Sl   Mar25  27:37 /opt/firefox/firefox
rodrigo   8897  0.0  0.1 108672 10580 pts/20   S+   15:02   0:00 /opt/firefox/firefox https://www.google.com
rodrigo   8901  0.0  0.0      0     0 pts/20   Z+   15:02   0:00 [firefox] <defunct>
rodrigo   8932  0.0  0.1 108672 10580 pts/20   S+   15:02   0:00 /opt/firefox/firefox https://www.google.com
rodrigo   8936  0.0  0.0      0     0 pts/20   Z+   15:02   0:00 [firefox] <defunct>
rodrigo  18522  0.0  0.1 108672 10576 pts/10   S    Mar25   0:00 /opt/firefox/firefox https://nylas.zendesk.com/hc/en-us/sections/203638587-N1
rodrigo  18525  0.0  0.0      0     0 pts/10   Z    Mar25   0:00 [firefox] <defunct>

```

Is related a with shell.openExternal, in Linux is a wrapper for `xdg-open`, if i  execute a command into the shell like `xdg-open example.com` open the tab in Firefox

**Comment by mbilker** [comment]
In relation to @roramirez 's post, Electron does use `xdg-open` on Linux through `shell.openExternal`. It should open a new tab, but it seems that Firefox ends up in a weird state from the zombies in that process list.

From my experience, N1 gets stuck if Chrome is closed because the Chrome command called by `xdg-open` does not exit. I need to open Chrome separately if I want N1 to still function.

**Comment by bengotow** [comment]
A fix for this landed upstream in Electron 3 days ago and will most likely make it into the next N1 release. https://github.com/electron/electron/pull/5072. Stay tuned!

**Comment by bengotow** [comment]
Hey folks—this should be fixed in `0.4.32`, which shipped yesterday. Cheers!

**Comment by roramirez** [comment]
Thanks @bengotow, i will test.

Regards!

**Comment by roramirez** [comment]
@bengotow 

I testing electron v0.37.8 and v0.37.7 with N1 0.4.32 and master branch but the problem is still.

xdg-open on my system is  1.1.0 rc1

**Comment by horaciojcfilho** [comment]
This problem still on latest release :(

**Comment by roramirez** [comment]
Yes @horaciojcfilho, the problem is still. @bengotow can you check?

I really think  is other the problem, is related with some component to  broke  the shell.External, not a electron problem, you can check test https://github.com/nylas/N1/issues/1716#issuecomment-202124188

**Comment by bengotow** [comment]
Re-opening this issue and merging in #2932

**Comment by grinich** [comment]
@roramirez Is this still happening?
