### ISSUE TITLE
Can't see inline images in email

### ISSUE THREAD

**Issue by tundal45** [nylas/N1#621]
I am seeing this instead of the image on OSX Yosemite (10.10.5).

![monosnap 2015-12-08 10-23-59](https://cloud.githubusercontent.com/assets/59220/11664326/f87504aa-9d95-11e5-87ba-482b3041d53b.png)

**Comment by bengotow** [comment]
Hey! This is being fixed in the next release, which should be out tomorrow. Stay tuned :-)

**Comment by Yerlix** [comment]
I still have this issue. The output is a little different:

![image](https://cloud.githubusercontent.com/assets/3891388/11834741/7e919384-a3cf-11e5-8c53-bdcca0d6baa2.png)

When I check the path, the folder nor the file exists.

I'm using OSX Yosemite (10.10.5) and N1 version 0.3.32

**Comment by ambarshante** [comment]
Facing the same issue. I'm running the latest version of N1 (0.3.32-b11131d). Screenshot below.

![screen shot 2015-12-22 at 5 14 50 pm](https://cloud.githubusercontent.com/assets/6899337/11954584/d09cdb48-a8cf-11e5-8f00-676886c7243b.png)

**Comment by bengotow** [comment]
Hey folks—can you check to see that you have free disk space and that the `~/.nylas/downloads` folder exists? Seems like this is still happening, but I'm not sure what would cause the attachment downloads to fail.

**Comment by awmartin** [comment]
Yes, the folder exists and I have disk space. It seems that inline images aren't treated as attachments in these cases and are thus never downloaded.

**Comment by Yerlix** [comment]
The folder exists here as well. And I've enough free space (100+ GB)

What I've noticed is that the download folder exists, but the folder inside the download folder (which should contain the images itself) doesn't.

**Comment by bengotow** [comment]
Oh interesting—can you look at the app's activity panel (Cmd-Option-W on the Mac) and see if we're attempting to download the attachments? When you view a message that has un-downloaded attachments, you should see entries like this in the Activity tab of the window:

![image](https://cloud.githubusercontent.com/assets/1037212/12691531/73c36a1e-c6a1-11e5-8277-5c801a580b88.png)

I think there are two things that could be going on:

- We could be failing to convert the inline images into attachments on our backend, so the app essentially doesn't see any files it needs to download. We'd need to investigate the formatting of the messages and see if there's an encoding / header / etc. that we're not parsing correctly.

- The requests for the attachments could be failing for some reason. In that case, the requests will appear red in that Activity view.

(sidenote: the app doesn't actually use curl, we just display requests that way for convenience!)

**Comment by Yerlix** [comment]
I don't see any requests for files, only for threads.
I've dubbel checked the  `~/.nylas/downloads/` folder just in case I've missed something, but the image isn't there.

So I guess the problem is that the images just aren't seen as downloadable items. In the activity window, all I could see was succeeded requests.

**Comment by rzierhofer** [comment]
Hi there guys... same issue over here. No inline images displayed/loaded.
OS X El Capitan 10.11.3

**Comment by dfleury** [comment]
Same here. I'm using Yosemite 10.10.5
I've checked the download folder and activity window but there is nothing different from what @Yerlix said.
The folder specific for the email attachments neither exists. Inspecting the generated html, the image tag appears to be ok, however the file isn't there.
So I inspected the image directly at gmail and concluded that gmail was giving me a png blob starting with:
```
PNG


IHDRÞ¸Â&g
```

However, N1's image path is for a file with .jpg as extension. I don't know if you re-encode the image in your servers but I hope this helps.

**Comment by ghost000cs** [comment]
Same issue as [this](https://github.com/nylas/N1/issues/1259)?

Has anyone tried changing the attachment setting from "Manually" to "When Read"? It does solve the issue for me.

I am using Windows 10.

**Comment by Yerlix** [comment]
@ghost000cs setting it to "When read" does solve this now. The setting was set to "When Received".
I'm going to see if this simple setting keeps on working.

**Comment by bellebethcooper** [comment]
I can confirm on El Capitan that changing to "When read" fixed this problem for me.

**Comment by almoore** [comment]
I am also seeing this issue. I am on an Ubuntu 14.04 machine. When I look at the debug info it shows me that there is an issue more with embedded iframe reference images. It seems to download them to the `~/.nylas/dowloads` area then then does an absolute unix reference to to the filesystem without prepending it as a file prefix.

`<img id="header-avatar-image" class="image_fix" src="/home/user/.nylas/downloads/c2arhjwn71qchlor7c5ebvetr/Unnamed Image.jpg" height="32" width="32" border="0" style="border-radius: 3px; vertical-align: top">`

The system html then interprets that as a local web reference to the iframe, and asks the server for that file which does not exist. So, if you either did not  download these ones or prepend the `file://` prefix this would work.

**Comment by bengotow** [comment]
Hey folks—thanks for debugging this further. Will try to reproduce by changing the attachment setting and see if that narrows it down. Cheers—

**Comment by bengotow** [comment]
I've confirmed that there are two separate bugs causing problems here:

- If you choose "On Receive", we only download attachments when you receive mail. So if you view a message that was initially received before you even installed N1, we never attempt to fetch the attachments. I've fixed this and added spec coverage in f1cd1056cc9bb3703b0030389c4522e06c3e6402.
- For image attachments we display inline, we don't provide any way to trigger the "manual" download (which would normally be triggered by clicking the attachment.) We should probably just show images as files when you have "download attachments manually" enabled.

**Comment by richarddewit** [comment]
@bengotow - it should be a great feature to include something of a header-type-bar-thingy, like in Thunderbird or Outlook, saying:

> Images are not being showed because you opted to download them manually. Click here to download them.

**Comment by jcguinea** [comment]
The inconvenient of select DOWNLOAD ATTACHMENTS WHEN RECEIVE or READ is that it even download the attach documents (doc, ppt, xls, pdf). It will be better that it just download the images and not the attach docuements

**Comment by mbilker** [comment]
Is this still an issue as of 0.4.19?

**Comment by amccloud** [comment]
I still get emails where the images refuse to load.

**Comment by akshaynhegde** [comment]
Am facing a similar issue. Images in the emails I get from Jira never load. The problem has been there from a many versions and it not fixed in the latest version (0.4.25-a22631a)
![screen shot 2016-04-14 at 10 14 17 am](https://cloud.githubusercontent.com/assets/3814615/14517723/60449b98-022e-11e6-8613-eab501c152a6.png)

**Comment by bengotow** [comment]
Hey @akshaynhegde — can you let me know what setting you've chosen here? ![image](https://cloud.githubusercontent.com/assets/1037212/14541724/596d655e-0259-11e6-9b32-c196a41d81c8.png). Could you also try viewing one of the Jira emails and then opening the Chromium Developer Tools (Cmd-Option-I on a Mac) and see if there are any failed requests in the console? It' be interesting to dig in further and see if the app is damaging the HTML of the email, or not trying to request the images at all.

If you have download attachments "manually" enabled, and the images are sent as inline attachments rather than URLs in the HTML, you'll need to choose "Load images" before they'll render.

**Comment by akshaynhegde** [comment]
Hi Ben,

  

Thank you for getting back to me. Download attachment settings have been set
to "When Read" for me.

  

I checked the console as you suggested and there indeed are a few 404 errors
for the images. Here is a screenshot.

  

Let me know if you need anything else to debug the issue.

  
Regards,

Akshay Hegde

  

On Apr 15 2016, at 1:29 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey [@akshaynhegde](https://github.com/akshaynhegde) — can you let me know
what setting you've chosen here? [![image](https://cloud.githubusercontent.com
/assets/1037212/14541724/596d655e-0259-11e6-9b32-c196a41d81c8.png)](https://cl
oud.githubusercontent.com/assets/1037212/14541724/596d655e-0259-11e6-9b32-c196
a41d81c8.png). Could you also try viewing one of the Jira emails and then
opening the Chromium Developer Tools (Cmd-Option-I on a Mac) and see if there
are any failed requests in the console? It' be interesting to dig in further
and see if the app is damaging the HTML of the email, or not trying to request
the images at all.

>

> If you have download attachments "manually" enabled, and the images are sent
as inline attachments rather than URLs in the HTML, you'll need to choose
"Load images" before they'll render.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/621#issuecomment-210123195)![](https://github.com/notifications/beaco
n/ADo012SnK7rK1IkIlu5xcYcWR3ZvasVLks5p3pydgaJpZM4GxO3N.gif)

**Comment by akshaynhegde** [comment]
Hi Ben,

  

Any updates? I still don't see those images in the latest version.

  

Regards,

Akshay Hegde

  

On Apr 15 2016, at 8:07 am, Akshay Hegde &lt;akshaynhegde@gmail.com&gt; wrote:  

> Hi Ben,

>

>  

>

> Thank you for getting back to me. Download attachment settings have been set
to "When Read" for me.

>

>  

>

> I checked the console as you suggested and there indeed are a few 404 errors
for the images. Here is a screenshot.

>

>  

>

> Let me know if you need anything else to debug the issue.

>

>  
Regards,

>

> Akshay Hegde

>

>  

>

> On Apr 15 2016, at 1:29 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

>> Hey [@akshaynhegde](https://github.com/akshaynhegde) — can you let me know
what setting you've chosen here? [![image](https://cloud.githubusercontent.com
/assets/1037212/14541724/596d655e-0259-11e6-9b32-c196a41d81c8.png)](https://cl
oud.githubusercontent.com/assets/1037212/14541724/596d655e-0259-11e6-9b32-c196
a41d81c8.png). Could you also try viewing one of the Jira emails and then
opening the Chromium Developer Tools (Cmd-Option-I on a Mac) and see if there
are any failed requests in the console? It' be interesting to dig in further
and see if the app is damaging the HTML of the email, or not trying to request
the images at all.

>>

>> If you have download attachments "manually" enabled, and the images are
sent as inline attachments rather than URLs in the HTML, you'll need to choose
"Load images" before they'll render.

>>

>> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/621#issuecomment-210123195)![](https://github.com/notifications/beaco
n/ADo012SnK7rK1IkIlu5xcYcWR3ZvasVLks5p3pydgaJpZM4GxO3N.gif)

**Comment by nowill** [comment]
this bug still there, will it be fixed in the next version?

**Comment by luishdez** [comment]
facing the same problem :(

![nylas-bug](https://cloud.githubusercontent.com/assets/38347/15943768/df5eae68-2e8a-11e6-8306-46a50320c1be.png)

**Comment by tthaumaturgist** [comment]
I'm running into a slightly different version of this (more akin to the associated issue "Image not being downloaded from Gmail #1259"). I'm running N1 0.4.40 on Windows 10 and use only gmail accounts. Attachments are set to download when read. When I try to save an attachment to a specific folder with a filename extension that isn't exactly correct (in my case, .d	ocx -- I notice in the above comment something like .png@[alphanumeric string]), it throws the "Uncaught Error: ENOENT: no such file or directory, open '[file path and name].d	ocx'"-type errors from the associated issue. It peacefully downloads from the gmail webapp.

Curiously, on my OSX 10.11.5 laptop running the same version (0.4.40-85cf726, to be specific), N1 saves the file to a specified folder without complaint.

**Comment by marszall87** [comment]
I have the same problem, I've noticed that JIRA adds a `<base href="..."/>` tag to the e-mail content, maybe that's the reason?

**Comment by annielcook** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3496

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!

**Comment by moesy** [comment]
I'm having the same issue on v 0.4.401
