### ISSUE TITLE
Remove `INBOX.foo` prefix from folder names (fastmail)

### ISSUE THREAD

**Issue by ricklupton** [nylas/N1#66]
With my Fastmail account, all the folders show up in the sidebar as "INBOX.FolderA", "INBOX.FolderB" etc. Can this prefix be removed in the UI?

**Comment by bengotow** [comment]
Hey @ricklupton — yep, definitely. We automatically scrub things like `[Gmail]/Inbox`, but our logic must not be identifying the INBOX prefix. I'll file this with our backend team and we'll get it fixed.

**Comment by dougmorin** [comment]
@bengotow Will it be possible to specify a "path prefix" with this added functionality, or should I create a new issue for this?

**Comment by enoversum** [comment]
I can confirm this here as well for IMAP accounts.

**Comment by khamidou** [comment]
Fixed in https://github.com/nylas/sync-engine/commit/a4708bb220677b86dd0ceff1f1d9b47bedc90bff.

**Comment by 50l3r** [comment]
I have the same problem. Can i fix this?

**Comment by enoversum** [comment]
@50l3r It is still not solved as it seems. See below on the screenshot.
![screenclip](https://cloud.githubusercontent.com/assets/8190174/14113751/9673ef2c-f5d4-11e5-8b65-b3cb50e62413.png)

**Comment by 50l3r** [comment]
ok I wait impatiently :)

**Comment by m3adi3c** [comment]
I want it gone as well! :)

**Comment by olimortimer** [comment]
Just started using N1, and seeing INBOX. on all my folders is getting pretty annoying

**Comment by rgruyters** [comment]
Same issue here. I still see INBOX. prefixes

**Comment by 5qian** [comment]
Same issue here. INBOX. prefixes still exist.
