### ISSUE TITLE
Nylas does not remember window fullscreen state

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#671]
Hi
When you open the Nylas app to use it, it opens not full windows, even you closed it like that, and the new opened window covers the bottom bar of Windows 10.
Thanks

**Comment by jstejada** [comment]
hey @csimonmoi, we fixed this so now the app remembers if you closed it in fullscreen mode and restores fullscreen. sorry for the delay!

**Comment by csimonmoi** [comment]
No it's not fixed. When you open the app for THE FIRST TIME after computer
booted up for THE FIRST TIME then the app does not fit well in the main window
and ALSO the column come back to the standard view and width.

They both DO NOT remember.

hope this time it's clearer and will help.

  

  

**  
**

> On Jan 13 2016, at 12:18 am, Juan &lt;notifications@github.com&gt; wrote:  

>

> Closed [#671](https://github.com/nylas/N1/issues/671).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/671#event-513074393).![](https://github.com/notifications/beacon/APTa
dlrgS3NLTzJFKaAGEqSy4a7SGqBNks5pZYE9gaJpZM4GzjqX.gif)

**Comment by jstejada** [comment]
Hi @csimonmoi, what version of N1 are you running? Is your windows taskbar hidden? Try updating to the latest version and let me know how it works.

**Comment by csimonmoi** [comment]
Latest version And no My task bar is Not hidden. Remember thst My spellate
checker top id Not working whatever language You choose.
Il 13/Gen/2016 21:01, "Juan" <notifications@github.com> ha scritto:
