### ISSUE TITLE
Feature Request: Ability to change Account From address in the New Message window

### ISSUE THREAD

**Issue by fjarrett** [nylas/N1#712]
Occasionally you quickly open the New Message window and start composing your very important email only to discover moments later that the From address isn't correct. This of course is because you were checking email in a different account at the time you opened the New Message window, so now you are locked into the context of that account.

OK let's see here...I have to copy my entire message (sorry Subject field), open up the correct account, launch the New Message window again, paste in the message, remember who I was sending this to...hmmm, what was my subject again? This is a bad UX.

Ideally, a user should be able to painlessly change this on-the-fly from the compose window to any other account that has been set up.

The current design of the field even gives the impression that it _is_ editable, but it is not.

<img width="804" alt="new-message" src="https://cloud.githubusercontent.com/assets/522158/11802743/a1ae9cac-a2b9-11e5-9d2f-e1d53ca64cda.png">

**Comment by jclusso** [comment]
+1

**Comment by fjarrett** [comment]
Now that we have Aliases (#234, #414, #662) it would be awesome if this feature was able to distinguish primary account addresses vs. aliases in the UI, where alias addresses would be nested beneath primary accounts.

I was envisioning something like this:

<img width="473" alt="change-from-with-aliases" src="https://cloud.githubusercontent.com/assets/522158/11889505/8574c608-a50f-11e5-8f3d-60c9664215e0.png">

Additionally, account-specific signatures (#213) and alias-specific signatures (#723) would need to live update inside the composition window whenever the From account is changed, which I imagine could be tricky.

**Comment by jclusso** [comment]
I really hope these features get added soon because this is probably the best mail client that exists and these are the only reasons I can't use it as my main client since I have multiple aliases and signatures and 4 gmail accounts.

**Comment by pkortge** [comment]
+1

**Comment by jstejada** [comment]
Merging into #537, since this is fixed on that branch. Stay tuned! Heading to beta shortly.

**Comment by jacobmischka** [comment]
Sorry, is this really fixed now? I can't seem to be able to do it.

**Comment by jstejada** [comment]
Hi @jacobmischka , yes this should be fixed. Are you seeing any errors?

**Comment by jacobmischka** [comment]
Sorry, I was just about to edit, I see that this is indeed fixed when composing new emails, but not when replying.

I think #811 should be reopened, since it still seems to be impossible to do this when replying, unless I'm missing something.

**Comment by armnrd** [comment]
@jacobmischka @jstejada Can confirm that it is still not possibly to change addresses while replying ([#811](https://github.com/nylas/nylas-mail/issues/811)).
