### ISSUE TITLE
UTF-8 subject not parsed correctly

### ISSUE THREAD

**Issue by yalon** [nylas/N1#789]
Hi,

N1 shows a lot of promise, it's about time :)

I have some emails that their UTF-8 subject is not parsed correctly and is left as-is. Here's an excerpt from the original message of such an email (which BTW would also help if we had an option to see):

```
Date: Mon, 21 Dec 2015 07:11:38 +0000
Subject: =?utf-8?B?15PXmdeV15XXlyDXmdeV150g15TXoteR15XXk9eUINeU16fX?=
 =?utf-8?B?ldeT150g15zXkCDXoNeh15LXqA==?=
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64
``` 

If there's anything I can add please let me know.
Thanks,
Tal

**Comment by mbilker** [comment]
Hey @yalon, do you have a picture of what shows in N1?

I decoded the title with `mimelib` for Node and decoded the title to:
```
> mimelib.decodeMimeWord('=?utf-8?B?15PXmdeV15XXlyDXmdeV150g15TXoteR15XXk9eUINeU16fXldeT150g15zXkCDXoNeh15LXqA==?=')
'דיווח יום העבודה הקודם לא נסגר'
```

**Comment by yalon** [comment]
Hi, thanks for looking into this so quickly and apologies for the late response.

Yes, mimelib got it right - that's what was supposed to appear, and here's a capture from the Subject line in the mail pane (tried w/ version 0.3.43-b95f1f7)

<img width="624" alt="screen shot 2016-01-17 at 23 07 27" src="https://cloud.githubusercontent.com/assets/347216/12379998/e2b5086e-bd6f-11e5-96a7-ab832beca9dd.png">

Thanks!

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!

**Comment by tezer** [comment]
No, it's not fixed. I have all attachments in this form. Version 2.0.31, Ubuntu 17.04
Also, occasionally, the message body is also broken, e.g. 
�M��N�0�_�����Z� T"�TĐ@nb%Iن�[C;O��f���o��F�r�������ά���5�>§}��w��͆�������:Cg�,Թ�-r��Y�5/΃oˮ�v�ݩO���k�>w�i�}+�UL�I΢��KV��5��g}�i����K��|Hӿ���2CI�� p5��5�0jD���1ʹ�r�K�W�b)S.���#��� ��i���dɭ�2O�$��ֵ�RZMH���H�,���U�g���9[�w
