### ISSUE TITLE
Feature Request: Reply to email with another account

### ISSUE THREAD

**Issue by sispus** [nylas/N1#811]
Is it possible to reply a mail as another sender account than receiver one? I want to have possibility to change the sender while replying a mail.

**Comment by grinich** [comment]
Hi @sispus do you mean via email aliases?

**Comment by sispus** [comment]
For example, I receive a mail in inbox of a@mail.com. I want to reply it by my other mail account, b@mail.com. Or, I just want to see and change the 'sender' of any sending mail, in 'send' popup window for example, besides 'to' and 'bcc' etc.

**Comment by fjarrett** [comment]
#712 is related.

**Comment by jstejada** [comment]
hey! merging this into #712

**Comment by koenpunt** [comment]
Even though this has been merged (twice), it unfortunately still isn't possible to select a different sender, like I could do in Apple Mail

**Comment by anthonysexton** [comment]
@jstejada this is different to #712 because it involves selecting a different from address when replying (#712 is about a new email).

+1 for this also.

**Comment by adnanoner** [comment]
Could this be issue reopened? I don't see that this is solved.

**Comment by armnrd** [comment]
Can confirm that this feature has still not been implemented in 2.0.32.
