### ISSUE TITLE
Gmail shortcuts: x does not select the message, o does not open the message

### ISSUE THREAD

**Issue by alecgorge** [nylas/N1#827]
Looking at the shortcuts listed under settings, it would seem that N1 supports using <kbd>x</kbd> to select messages in the messages list as Gmail does to achieve a similar effect as <kbd>⌘ + Click</kbd>.

However, this is not working for me on `0.3.32-b11131d`.

**Comment by alecgorge** [comment]
In addition, <kbd>o</kbd> does not open a message while moving between items while more than 1 is selected.

**Comment by grinich** [comment]
This is fixed!

**Comment by alecgorge** [comment]
Awesome! When will this make it into a release?

**Comment by alecgorge** [comment]
@grinich I just tested this in `0.4.30-dd40540` and it still doesn't work
