### ISSUE TITLE
Trash Icon Missing -- No ability to Trash emails

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#872]
This issue was posted by `vaska` on the Nylas Slack chat.

With two accounts using IMAP as the provider, the Trash icon is absent on the secondary account.

My guess is there is some flag in the Sync Engine that tells N1 the folder is immutable. My hypothesis is it is a shared folder and the user does not have permission to modify the folder, but since the accounts belong to `vaska` I don't know what could cause this issue to only affect one of two accounts.

**Comment by spang** [comment]
Hi @mbilker, we're not really able to debug this further without knowing which two accounts are affected.

**Comment by mbilker** [comment]
Thanks anyway @spang. You (or Nylas person) could get in touch with `vaska` on the Slack chat to debug this on your side. I don't have those permission levels.

**Comment by FLAVIAN85** [comment]
Hi there.
I really like your programme. But there are some issues with it.
All my IMAP Folders appear with the prefix INBOX.whatever. I have browsed git hub. This was fixed supposadely. https://github.com/nylas/N1/issues/66 But it is still not working for me.

And then there is no delete button when I open an email. And when I hover over an email it only shows the archive button.
![bildschirmfoto 2016-01-15 um 22 10 54](https://cloud.githubusercontent.com/assets/17007014/12719711/33e7dbde-c8f7-11e5-8a09-b2fa34fb8b2d.png)
![bildschirmfoto 2016-02-01 um 15 20 13](https://cloud.githubusercontent.com/assets/17007014/12719738/5a2c6e40-c8f7-11e5-92be-ceac5034f135.png)

**Comment by droplab** [comment]
I'm also having this problem. I really love the UI of this mail app -- better than any I've ever used including apple mail. I have the same issue with all the folders are prefixed INBOX and special folders (trash, sent) don't show up for my IMAP account -- all works fine for my gmail account though.

<img width="203" alt="screen shot 2016-02-06 at 3 01 00 pm" src="https://cloud.githubusercontent.com/assets/201657/12869941/d50a4e4a-cce2-11e5-9e4d-b6d395a66e53.png">

Thanks!

**Comment by laughedelic** [comment]
I don't have this trash icon at all! :cold_sweat:

<img width="127" alt="screen shot 2016-02-10 at 16 02 34" src="https://cloud.githubusercontent.com/assets/766656/12950915/f6c429f4-d00f-11e5-8c48-4996c674f74e.png">

I use only one gmail account.

**Comment by FLAVIAN85** [comment]
By Trash Icon I meant  the trash icon in the upper bar, when you open up an e-mail.
Also when you hover over your inbox list of mails, I don’t get a trash icon.
And how that you mention it, as you can see in the screen shots the Trash can is also not displayed in the side bar.

**Comment by mbilker** [comment]
@laughedelic I assume you used the Gmail and not the IMAP option when setting up your account. Is there any Deleted or Trash label present under labels?

**Comment by laughedelic** [comment]
@FLAVIAN85 I didn't notice that you also don't have this folder, I just saw the @droplab's screenshot with the folder. Anyway, I also don't have the delete button in the toolbar (since the last big update).

Probably it's a duplicate, but I've opened a new issue: https://github.com/nylas/N1/issues/1290

**Comment by mbilker** [comment]
A real solution to the problem is to allow the user to set which folder messages should go if it autodetects incorrectly. Maybe stick it under Advanced Options for an Account. This requires coordination between the Sync Engine and the N1 teams.

**Comment by laughedelic** [comment]
@mbilker yes, I use Gmail type of account, not generic IMAP. I think I had `Trash` label before, but not it's gone. Although if I open gmail.com, there is a `Trash` label.

**Comment by laughedelic** [comment]
Guys, please check my https://github.com/nylas/N1/issues/1290#issuecomment-182437346, I found a solution for myself, probably it'll work for you too :wink:

**Comment by FLAVIAN85** [comment]
Sadly does not work for me! I used generic IMAP on a private server , not Gmail :(

**Comment by thecristen** [comment]
Just want to chime in that I was also unable to delete email from one of my accounts. It was an IMAP account set up through Webfaction. I decided to log into it via webmail to see if there was some setting I could toggle, and while I was cleaning up some folders (I had both a Trash folder and a Deleted Messages folder) N1 re-synced and I got my Trash folder ¯\_(ツ)_/¯ so now all's good. Just posting this in case it helps someone..

**Comment by bengotow** [comment]
Hey folks! This should be resolved with recent fixes to our sync engine. Can you try again and see if the trash appears for you?

**Comment by FLAVIAN85** [comment]
Sorry. No :( I installed the newest Nylas version. Still no luck :(
Also the weird „INBOX.“ prefix is still there before all my folders.

**Comment by thosgood** [comment]
I'm still having the issue that neither my 'Sent Items' nor my 'Deleted Items' folders on my IMAP account are detected by N1 (they don't appear anywhere at all on the sidebar).

**Comment by Sammy83** [comment]
Same here. Just learned about Nylas N1 yesterday, installed it and added one of my own IMAP accounts today to start testing it. There is no option to delete a message. There is no Trash or Sent folder in the left sidebar and no trash icon in the top bar of emails or conversations.

The only thing that comes even close is the "Deleted Messages" folder, but there is no shortcut for that one.

Everything works fine with Airmail or Apple Mail with my IMAP accounts, so I think there is something wrong with the way it syncs or maybe it does not sync everything correctly.

What can I do to help to fix these issues?

**Comment by Sammy83** [comment]
And not sure where to put feature requests or ideas but I like the idea of having multiple signatures per mail address. I usually have one in english and one in german and select in Apple Mail for each email which one to choose. One is set as default.

But in Nylas N1 it seems as if I can only assign one signature per mail account. Is that correct?

**Comment by jackiehluo** [comment]
Merging into #1457, because it sounds like the same issue.

@Sammy83 Signature changes are coming, courtesy of @annielcook! 🎉
