### ISSUE TITLE
`#` only deletes one message when all messages are selected via `*->a`...

### ISSUE THREAD

**Issue by bmakuh** [nylas/N1#972]
...using Gmail shortcuts. If you select multiple conversations with `click->shift->click` and press `#` then all the conversations are deleted.

Furthermore, if you use `*->a` and then use the `delete` key, all messages are moved to the trash.

**Comment by jstejada** [comment]
hey @bmakuh , I'm not able to replicate this. `#` is working as expected, as well as `* a` and `delete`. This should be addressed in the latest version. If you keep having trouble feel free to reopen this.

**Comment by bmakuh** [comment]
Hmm, it's still not working for me. The only way `* a` works for me is if I actually click on the delete button in the header. Not really a big deal though, honestly. Definitely shouldn't be a high priority unless you get other people reporting it too.

**Comment by jstejada** [comment]
this might be related to #939

**Comment by jackiehluo** [comment]
Going to close this issue for now due to inactivity! Let us know if it's still an issue.
